# Fit change models, linear or nonlinear, to one or many trajectories,
# curve by curve or as a mixed-effects model.
#' Analysis of Change: Fit Change Models to One or Many Trajectories
#'
#' Fits a change model to longitudinal data: any of the package's four
#' nonlinear change models (negative exponential, logistic, Gompertz,
#' Richards; the parameterizations of Kelley, 2005, 2008, exactly as
#' generated by the \code{simulate_longitudinal_*()} simulators) or a
#' polynomial of any order (the linear change model of
#' \code{\link{simulate_longitudinal_polynomial}}). Two estimation
#' methods are offered. The default, \code{method = "two_stage"}, fits
#' each unit's curve separately, using only that unit's data, and then
#' summarizes the unit-level parameters: their mean, their standard
#' deviation and variance across units (the individual differences),
#' and the standard error of the mean. \code{method = "mixed"} fits the
#' proper random-coefficients mixed-effects model simultaneously, with
#' every parameter carrying a random effect, so the reported
#' between-unit spread is a variance component purged of estimation
#' noise. With a single trajectory (\eqn{N = 1}, or \code{id = NULL})
#' the two-stage method reduces to one least squares fit of that unit's
#' change, reported with its standard errors.
#'
#' @param data A \code{data.frame} in long format: one row per
#'   observation, as returned by the \code{simulate_longitudinal_*()}
#'   simulators.
#' @param id Name of the column identifying units (persons, animals,
#'   trees, classrooms). \code{NULL} treats all rows as a single
#'   trajectory (\code{method = "two_stage"} only).
#' @param time Name of the time column.
#' @param outcome Name of the outcome column.
#' @param model Which change model to fit:
#'   \code{"negative_exponential"} (parameters alpha, zeta, gamma),
#'   \code{"logistic"} (alpha, beta, gamma, zeta), \code{"gompertz"}
#'   (alpha, beta, gamma, zeta), \code{"richards"} (alpha, beta,
#'   gamma, delta, zeta), or \code{"polynomial"} (coefficients
#'   \code{b0} through \code{bP}, with the order \eqn{P} set by
#'   \code{order}). See the corresponding simulator's help page for
#'   what each parameter means.
#' @param method How the model is estimated. \code{"two_stage"} (the
#'   default) fits one curve per unit, each from that unit's data alone,
#'   and summarizes across units; it is transparent, works at
#'   \eqn{N = 1}, and never lets one unit's data influence another's
#'   fit. \code{"mixed"} estimates the random-coefficients model
#'   simultaneously: \code{lme4::lmer()} for the polynomial (a linear
#'   mixed model) and \code{nlme::nlme()} for the nonlinear curves
#'   (started at the two-stage estimates), with uncorrelated random
#'   effects on every parameter. See Details for how to choose.
#' @param order Polynomial order \eqn{P} when \code{model =
#'   "polynomial"} (1 is straight-line change, 2 quadratic, and so on).
#'   Default \code{1}. Ignored for the nonlinear models.
#' @param start Optional named numeric vector of starting values for a
#'   nonlinear model's parameters, used for every unit (and, under
#'   \code{method = "mixed"}, for the fixed effects). \code{NULL}
#'   (default) derives data-driven starting values per unit (see
#'   Details). Ignored for the polynomial, whose fit is closed form.
#' @param maxiter Maximum number of iterations passed to
#'   \code{\link[stats]{nls}} (and, under \code{method = "mixed"}, to
#'   the nonlinear mixed-effects optimizer). Default \code{500}.
#'
#' @return A \code{data.frame} with one row per model parameter and
#'   columns
#'   \describe{
#'     \item{\code{term}}{The parameter name.}
#'     \item{\code{estimate}}{The mean of the unit-level estimates
#'       (two-stage; with one trajectory, that unit's estimate) or the
#'       fixed effect (mixed).}
#'     \item{\code{se}}{The standard error of \code{estimate}: the
#'       between-unit standard deviation over the square root of the
#'       number of fitted units (two-stage), the asymptotic standard
#'       error of the single fit (one trajectory), or the fixed-effect
#'       standard error (mixed).}
#'     \item{\code{sd_units}}{The between-unit standard deviation of
#'       the parameter: the spread of the unit-level estimates
#'       (two-stage; \code{NA} for a single trajectory) or the
#'       random-effect standard deviation (mixed).}
#'     \item{\code{var_units}}{The corresponding variance.}
#'   }
#'   Attributes: \code{"model"}, \code{"method"}, \code{"n_units"}
#'   (units supplied), \code{"n_used"} (units whose fit converged;
#'   equal to \code{"n_units"} under \code{method = "mixed"}),
#'   \code{"sigma"} (the level-one residual standard deviation),
#'   and \code{"per_unit_estimates"} (a units-by-parameters matrix:
#'   the separate unit-level estimates under two-stage, or the
#'   unit-level predictions \code{coef()} under mixed, which are
#'   shrunken toward the fixed effects).
#'
#' @details
#' \strong{Choosing between the methods.} The two-stage
#' (curve-by-curve) route is the transparent classic: every unit's
#' curve is inspectable, no unit's data influence another's fit, and
#' it is the only method available for a single trajectory. Its known
#' cost is that \code{sd_units} reflects the spread of
#' \emph{estimates}, which adds each fit's estimation noise to the
#' true individual differences; with short or noisy trajectories it
#' therefore overstates the population standard deviation. The mixed
#' method estimates that between-unit variation as a variance
#' component, separating it from level-one error, and borrows strength
#' across units, at the price of a harder estimation problem (and, for
#' the nonlinear curves, occasional convergence trouble; the fit is
#' started at the two-stage estimates, and a failure suggests
#' simplifying the model or falling back to two-stage). Under
#' \code{method = "mixed"} the random effects are uncorrelated across
#' parameters, matching the simulators' default.
#'
#' \strong{Relation to existing tools.} The two-stage method is the
#' idea behind \code{nlme::lmList()} and \code{nlme::nlsList()}, and
#' the mixed method wraps \code{lme4::lmer()} and \code{nlme::nlme()};
#' base R also ships self-starting curves (\code{SSasymp},
#' \code{SSfpl}, \code{SSgompertz}) in other parameterizations. What
#' this function adds is the package's landmark parameterizations (the
#' intercept-shifting \eqn{\zeta} floor, the Richards \eqn{\delta};
#' \code{SSgompertz}'s \eqn{a \exp(-b_2 b_3^x)} answers no substantive
#' question directly), the exact match to the
#' \code{simulate_longitudinal_*()} simulators so design studies close
#' the loop, one interface across linear and nonlinear change, and the
#' package's tidy summary with failed fits dropped under a single
#' counted warning.
#'
#' \strong{Units whose two-stage fit does not converge} are dropped
#' with a single warning reporting how many, and the effective count
#' is the \code{"n_used"} attribute. If no unit's fit converges the
#' function stops. The polynomial fit is closed form and does not
#' fail on any trajectory with at least \eqn{P + 1} occasions.
#'
#' \strong{Starting values.} Unless \code{start} is supplied, each
#' unit's nonlinear starting values are derived from that unit's data:
#' the floor and the span from early and late observations, the
#' inflection time from where the trajectory crosses the middle of its
#' range, the curvature from the time the trajectory needs to travel
#' the central half of its range, and, for the Richards model, a
#' logistic start (delta = 1). Cleanly measured trajectories rarely
#' need more; hard cases (very short series, strong decreasing curves,
#' near-flat change) may need an explicit \code{start}.
#'
#' @references
#' Kelley, K. (2005). \emph{Estimating nonlinear change models in
#'   heterogeneous populations when class membership is unknown: Defining
#'   and developing the latent classification differential change model}
#'   (Doctoral dissertation). University of Notre Dame.
#'
#' Kelley, K. (2008). Nonlinear change models in populations with
#'   unobserved heterogeneity. \emph{Methodology, 4}(3), 97--112.
#'
#' Pinheiro, J. C., & Bates, D. M. (2000). \emph{Mixed-effects models
#'   in S and S-PLUS}. Springer.
#'
#' Richards, F. J. (1959). A flexible growth function for empirical use.
#'   \emph{Journal of Experimental Botany, 10}(2), 290--301.
#'
#' @seealso The generators
#'   \code{\link{simulate_longitudinal_negative_exponential}},
#'   \code{\link{simulate_longitudinal_logistic}},
#'   \code{\link{simulate_longitudinal_gompertz}},
#'   \code{\link{simulate_longitudinal_richards}},
#'   \code{\link{simulate_longitudinal_polynomial}};
#'   \code{\link{plot_trajectories}} for plotting the data being fit;
#'   \code{nlme::lmList()}, \code{nlme::nlsList()},
#'   \code{lme4::lmer()}, and \code{nlme::nlme()} for the engines and
#'   their generalizations.
#'
#' @examples
#' # Simulate a Gompertz population with individual differences, then
#' # recover both the mean curve and the spread of its parameters.
#' set.seed(113)
#' d <- simulate_longitudinal_gompertz(
#'   n = 40, target_times = 0:10,
#'   fixed_parameters = c(alpha = 75, beta = 3, gamma = 0.55, zeta = 10),
#'   random_variances = c(alpha = 25, beta = 0.4, gamma = 0.005, zeta = 4),
#'   error_variance = 4
#' )
#' analysis_of_change(d, id = "id", time = "time", outcome = "y",
#'                    model = "gompertz")
#'
#' # The same data as a straight-line (order 1) polynomial: the linear
#' # model has nothing to say about floors, ceilings, or timing.
#' analysis_of_change(d, id = "id", time = "time", outcome = "y",
#'                    model = "polynomial", order = 1)
#'
#' # A single unit's trajectory: N = 1 is one fit, with asymptotic
#' # standard errors in place of between-unit spread.
#' one <- d[d$id == levels(d$id)[1], ]
#' analysis_of_change(one, id = NULL, time = "time", outcome = "y",
#'                    model = "gompertz")
#'
#' # The proper mixed-effects model, fit simultaneously across units:
#' # nlme::nlme() for a nonlinear curve, lme4::lmer() for the polynomial
#' # (the latter requires lme4 to be installed).
#' analysis_of_change(d, id = "id", time = "time", outcome = "y",
#'                    model = "gompertz", method = "mixed")
#' analysis_of_change(d, id = "id", time = "time", outcome = "y",
#'                    model = "polynomial", order = 1,
#'                    method = "mixed")
#'
#' @author Ken Kelley \email{kkelley@@nd.edu}
#'
#' @keywords models regression
#'
#' @export
analysis_of_change <- function(data, id, time, outcome,
                               model = c("negative_exponential",
                                         "logistic", "gompertz",
                                         "richards", "polynomial"),
                               method = c("two_stage", "mixed"),
                               order = 1L,
                               start = NULL,
                               maxiter = 500L) {
  model <- match.arg(model)
  method <- match.arg(method)
  polynomial <- model == "polynomial"

  if (polynomial) {
    if (!is.numeric(order) || length(order) != 1L || is.na(order) ||
        order < 0 || order != round(order)) {
      stop("'order' must be a single non-negative integer.", call. = FALSE)
    }
    order <- as.integer(order)
    par_names <- paste0("b", 0:order)
  } else {
    par_names <- .growth_curves[[model]]$par_names
  }

  if (!is.data.frame(data)) {
    stop("'data' must be a data.frame in long format.", call. = FALSE)
  }
  for (nm in c(time, outcome)) {
    if (!nm %in% names(data)) {
      stop(sprintf("Column '%s' is not in 'data'.", nm), call. = FALSE)
    }
  }
  if (!is.null(id) && !id %in% names(data)) {
    stop(sprintf("Column '%s' is not in 'data'.", id), call. = FALSE)
  }
  if (is.null(id) && method == "mixed") {
    stop("method = \"mixed\" needs several units: give 'id'. A single ",
         "trajectory is fit with method = \"two_stage\".", call. = FALSE)
  }
  if (!is.null(start)) {
    if (polynomial) {
      stop("'start' does not apply to the polynomial: its least squares ",
           "fit is closed form.", call. = FALSE)
    }
    if (!is.numeric(start) || is.null(names(start)) ||
        !setequal(names(start), par_names)) {
      stop(sprintf("'start' must be a named numeric vector over %s.",
                   paste(par_names, collapse = ", ")), call. = FALSE)
    }
    start <- start[par_names]
  }

  df_all <- data.frame(
    t_ = as.numeric(data[[time]]),
    y_ = as.numeric(data[[outcome]]),
    id_ = if (is.null(id)) factor("unit_1") else factor(data[[id]])
  )
  df_all <- df_all[stats::complete.cases(df_all), , drop = FALSE]
  df_all$id_ <- droplevels(df_all$id_)
  n_units <- nlevels(df_all$id_)

  rhs <- if (polynomial) {
    # Raw powers of time, the same terms the mixed branch uses; an
    # intercept-only formula covers order = 0, which stats::poly refuses.
    if (order >= 1L) {
      stats::as.formula(paste0(
        "y_ ~ ", paste0("I(t_^", seq_len(order), ")", collapse = " + ")))
    } else {
      y_ ~ 1
    }
  } else switch(model,
    negative_exponential = y_ ~ alpha + zeta * exp(-gamma * t_),
    logistic = y_ ~ alpha / (1 + exp(-gamma * (t_ - beta))) + zeta,
    gompertz = y_ ~ alpha * exp(-exp(-gamma * (t_ - beta))) + zeta,
    richards = y_ ~ alpha / (1 + delta * exp(-gamma * (t_ - beta)))^(1 / delta) + zeta
  )

  # ---------- Stage one: per-unit fits ----------
  # Run for both methods: two-stage needs them as the result, and the
  # nonlinear mixed fit needs them as starting values.
  pieces <- split(df_all, df_all$id_, drop = TRUE)
  fits <- vector("list", n_units)
  sigmas <- rep(NA_real_, n_units)
  for (i in seq_len(n_units)) {
    df <- pieces[[i]]
    if (nrow(df) < length(par_names)) next
    if (polynomial) {
      fit <- stats::lm(rhs, data = df)
      cf <- stats::coef(fit)
      if (anyNA(cf)) next
      names(cf) <- par_names
      fits[[i]] <- list(coef = cf,
                        se = stats::setNames(
                          summary(fit)$coefficients[, "Std. Error"],
                          par_names),
                        sigma = summary(fit)$sigma)
      sigmas[i] <- summary(fit)$sigma
    } else {
      sv <- if (is.null(start)) .growth_start_values(df$t_, df$y_, model) else start
      f <- tryCatch(
        stats::nls(rhs, data = df, start = as.list(sv),
                   control = stats::nls.control(maxiter = maxiter,
                                                warnOnly = FALSE)),
        error = function(e) NULL
      )
      if (!is.null(f)) {
        fits[[i]] <- list(coef = stats::coef(f)[par_names],
                          se = summary(f)$coefficients[par_names, "Std. Error"],
                          sigma = summary(f)$sigma)
        sigmas[i] <- summary(f)$sigma
      }
    }
  }
  ok <- !vapply(fits, is.null, logical(1))
  n_used <- sum(ok)
  if (n_used == 0L) {
    if (polynomial) {
      stop("No unit's curve could be fit: a polynomial of order ", order,
           " needs at least ", order + 1L, " occasions per unit.",
           call. = FALSE)
    }
    stop("No unit's curve could be fit. Supply 'start' values, or check ",
         "that the trajectories carry enough occasions for a ", model,
         " model.", call. = FALSE)
  }
  # matrix(), not t(vapply()): with a single parameter vapply returns a
  # bare vector, and t() would put units in columns instead of rows.
  est <- matrix(
    vapply(fits[ok], function(f) f$coef, numeric(length(par_names))),
    nrow = n_used, byrow = TRUE, dimnames = list(NULL, par_names))

  if (method == "two_stage") {
    if (n_used < n_units) {
      warning(sprintf(paste0("%d of %d unit fits did not converge and were ",
                             "dropped; summaries use the %d that did (the ",
                             "'n_used' attribute)."),
                      n_units - n_used, n_units, n_used), call. = FALSE)
    }
    if (n_used > 1L) {
      means <- colMeans(est)
      sds <- apply(est, 2, stats::sd)
      ses <- sds / sqrt(n_used)
      vars <- sds^2
    } else {
      means <- est[1L, ]
      ses <- fits[ok][[1L]]$se
      sds <- rep(NA_real_, length(par_names))
      vars <- rep(NA_real_, length(par_names))
    }
    sigma_out <- sqrt(mean(sigmas[ok]^2))
    per_unit <- est
  } else {
    # ---------- method = "mixed": the simultaneous model ----------
    if (polynomial) {
      if (!requireNamespace("lme4", quietly = TRUE)) {
        stop("method = \"mixed\" with the polynomial model requires the ",
             "'lme4' package. Install it with install.packages(\"lme4\").",
             call. = FALSE)
      }
      terms_txt <- if (order >= 1L) {
        paste0("I(t_^", seq_len(order), ")")
      } else {
        character(0)
      }
      fe <- paste(c("1", terms_txt), collapse = " + ")
      # A lone random intercept needs the single bar: lme4's double-bar
      # expansion rejects an intercept-only (1 || id_) term, and with one
      # random effect there is no correlation to suppress anyway.
      re_bar <- if (order >= 1L) paste0("(", fe, " || id_)")
                else "(1 | id_)"
      fml <- stats::as.formula(paste0("y_ ~ ", fe, " + ", re_bar))
      mfit <- lme4::lmer(fml, data = df_all)
      b <- lme4::fixef(mfit)
      means <- stats::setNames(as.numeric(b), par_names)
      ses <- stats::setNames(sqrt(diag(as.matrix(stats::vcov(mfit)))),
                             par_names)
      vc <- as.data.frame(lme4::VarCorr(mfit))
      re <- vc[vc$grp != "Residual" & is.na(vc$var2), ]
      re_name <- ifelse(re$var1 == "(Intercept)", "b0",
                        sub("^I\\(t_\\^(\\d+)\\)$", "b\\1", re$var1))
      sds <- stats::setNames(rep(NA_real_, length(par_names)), par_names)
      sds[re_name] <- re$sdcor
      vars <- sds^2
      sigma_out <- stats::sigma(mfit)
      pu <- as.matrix(stats::coef(mfit)$id_)
      colnames(pu) <- par_names
      per_unit <- pu
    } else {
      if (!requireNamespace("nlme", quietly = TRUE)) {
        stop("method = \"mixed\" with a nonlinear model requires the ",
             "'nlme' package. Install it with install.packages(\"nlme\").",
             call. = FALSE)
      }
      fixed_fml <- stats::as.formula(
        paste(paste(par_names, collapse = " + "), "~ 1"))
      random_fml <- nlme::pdDiag(stats::as.formula(
        paste(paste(par_names, collapse = " + "), "~ 1")))
      start_fixed <- colMeans(est)
      mfit <- tryCatch(
        nlme::nlme(rhs, data = df_all,
                   fixed = fixed_fml, random = random_fml,
                   groups = ~id_, start = start_fixed,
                   control = nlme::nlmeControl(maxIter = maxiter,
                                               msMaxIter = maxiter,
                                               returnObject = FALSE)),
        error = function(e) {
          stop("The nonlinear mixed-effects fit did not converge (",
               conditionMessage(e), "). The two-stage estimates are ",
               "available with method = \"two_stage\"; a simpler model ",
               "or explicit 'start' values may also help.", call. = FALSE)
        }
      )
      b <- nlme::fixef(mfit)
      means <- stats::setNames(as.numeric(b), par_names)
      ses <- stats::setNames(
        sqrt(diag(as.matrix(mfit$varFix))), par_names)
      vc <- nlme::VarCorr(mfit)
      sds <- stats::setNames(
        suppressWarnings(as.numeric(vc[par_names, "StdDev"])), par_names)
      vars <- sds^2
      sigma_out <- mfit$sigma
      pu <- as.matrix(stats::coef(mfit))
      colnames(pu) <- par_names
      per_unit <- pu
    }
    n_used <- n_units
  }

  out <- data.frame(
    term = par_names,
    estimate = unname(means[par_names]),
    se = unname(ses[par_names]),
    sd_units = unname(sds[par_names]),
    var_units = unname(vars[par_names]),
    stringsAsFactors = FALSE,
    row.names = NULL
  )
  attr(out, "model") <- model
  attr(out, "method") <- method
  attr(out, "n_units") <- n_units
  attr(out, "n_used") <- n_used
  attr(out, "sigma") <- sigma_out
  attr(out, "per_unit_estimates") <- per_unit
  .as_dmar_tbl(out)
}

# Data-driven starting values for one trajectory. The anchors: the
# floor and span from the early and late thirds of the series, the
# inflection time from the crossing of mid-range, and the curvature
# from the time needed to travel the central half of the range (a
# logistic covers its central half in about 2.2 / gamma time units).
.growth_start_values <- function(t, y, model) {
  o <- order(t)
  t <- t[o]; y <- y[o]
  n <- length(y)
  k <- max(1L, floor(n / 3))
  y_early <- mean(y[seq_len(k)])
  y_late <- mean(y[seq.int(n - k + 1L, n)])
  span <- y_late - y_early
  if (abs(span) < 1e-10) span <- diff(range(y)) + 1e-8
  t_range <- diff(range(t))
  if (t_range <= 0) t_range <- 1

  mid <- y_early + span / 2
  beta0 <- t[which.min(abs(y - mid))[1L]]
  q1 <- y_early + span * 0.25
  q3 <- y_early + span * 0.75
  t_q1 <- t[which.min(abs(y - q1))[1L]]
  t_q3 <- t[which.min(abs(y - q3))[1L]]
  spread <- abs(t_q3 - t_q1)
  if (spread <= 0) spread <- t_range / 4
  gamma0 <- sign(span) * 2.2 / spread

  switch(model,
    negative_exponential = c(alpha = y_late, zeta = y_early - y_late,
                             gamma = 3 / t_range),
    logistic = c(alpha = span, beta = beta0, gamma = gamma0,
                 zeta = y_early),
    gompertz = c(alpha = span, beta = beta0, gamma = gamma0,
                 zeta = y_early),
    richards = c(alpha = span, beta = beta0, gamma = gamma0,
                 delta = 1, zeta = y_early)
  )
}
